### ISSUE TITLE
[BOAT] Check for external invite links?

### ISSUE THREAD

**Issue by ghost** [powercord-org/powercord-backend#83]
Shouldn't the bot check for other URLs
Some services offer a custom vanity url type thing
For example, discordservers.com allows you to pick from
- discord.chat
- disc.gg
- discservs.co
So the bot should have a better checklist.
I'd add the three above
as well as 
- dsc.gg
- discord.io

I mean if someone wanted
They could get a (sub)domain make it redirect to an invite
And it would stay up until a mod notices.

**Comment by cyyynthia** [comment]
Instead of using a condescending tone and inappropriate language in an issue tracker you should have done your homework and would have noticed we do in fact [already look for certain known vanity invite websites](https://github.com/powercord-org/powercord-backend/blob/my-awesome-branch/packages/boat/src/modules/mod/automod.ts#L33).

While you are right and certain URLs you listed would go under our radar, and reporting it is appropriate, the use of inappropriate language here is not and will not be tolerated.

**Comment by ghost** [comment]
So fucking glad I got banned from powercord.
You guys have always been a bitch
